spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/${DB_SCHEMA}
    username: ${USERNAME}
    password: ${PASSWORD}
server:
  compression:
    enabled: true
    mime-types: application/octet-stream,application/json,application/xml,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}
  servlet:
    context-path: /lecturaDirectorio